name: CI
on:
  push:
  pull_request:
jobs:
  checks:
    name: Scalafmt/Scalafix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
      - run: ./bin/scalafmt --check
      - run: sbt fixCheck
