name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  unit:
    name: ${{ matrix.os }} jdk-${{ matrix.java }} unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        java: [8, 11]
        exclude:
          - os: windows-latest
            java: 8
          - os: macOS-latest
            java: 8
        include:
          - os: ubuntu-latest
            CACHE_PATH: ~/.cache/coursier/v1
          - os: macOS-latest
            CACHE_PATH: ~/Library/Caches/Coursier/v1
          - os: windows-latest
            CACHE_PATH: ~\AppData\Local\Coursier\Cache\v1
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: "adopt@1.${{ matrix.java }}"
      - uses: actions/cache@v1
        with:
          path: $CACHE_PATH
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier-
      - uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: |
            ${{ runner.os }}-sbt-${{ hashFiles('project/build.properties') }}-${{ hashFiles('project/plugins.sbt') }}
          restore-keys: ${{ runner.os }}-sbt-
      - name: Run unit tests
        run: |
          sbt test
        shell: bash
  native-image:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
        include:
          - os: macOS-latest
            artifact: fastpass-x86_64-apple-darwin
          - os: ubuntu-latest
            artifact: fastpass-x86_64-pc-linux
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v6
      - uses: olafurpg/setup-scala@v6
        with:
          java-version: graalvm@20.1.0
      - run: git fetch --tags
      - run: gu install native-image
      - run: sbt native-image
      - uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.artifact }}
          path: fastpass/target/graalvm-native-image/fastpass
